version: '3'

services:
  web:
   image: roger2113/imagehosting:backend
   ports:
    - "8080:8080"
   depends_on:
    - db

  db:
   image: roger2113/imagehosting:postgres
   restart: always
   volumes:
    - ./data/postgres:/data/postgres
   ports:
    - "5432:5432"

   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: pg123
    POSTGRES_DB: imagehosting
    PGDATA: /data/postgres