version: '3'

services:
  web:
   build: ./backend
   ports:
    - "8080:8080"
   depends_on:
    - db

  db:
   build: ./database
   restart: always
   volumes:
    - ./data/postgres:/var/lib/postgresql
   ports:
    - "5432:5432"
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: pg123
    POSTGRES_DB: imagehosting

